## Introduction to Numpy

#### **Name:Manuel Ibañez Salazar** <Insert name>


#### Import numpy

In [4]:
import numpy

In [5]:

import numpy as np

#### Matrix Operations with numpy

1. Create a 3x3 matrix in numpy with the following values: 

⎡ 1  2  3 ⎤ \
⎢ 4  5  6 ⎥ \
⎣ 7  8  9 ⎦ 

2.- Transpose the matrix and save it into a transpose variable \
3.- Add both matrix \
4.- Multiply both matrix



In [4]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [5]:
transpose = matrix.T

In [6]:
sum_result = matrix + transpose


In [7]:
product_result = np.dot(matrix, transpose)

In [8]:
print("Original Matrix:\n", matrix)
print("\nTransposed Matrix:\n", transpose)
print("\nSum of Matrix + Transpose:\n", sum_result)
print("\nMatrix Multiplication (Matrix x Transpose):\n", product_result)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Sum of Matrix + Transpose:
 [[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]

Matrix Multiplication (Matrix x Transpose):
 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


#### numpy indexing

1.- Create a numpy array [10, 20, 30, 40, 50, 60] \
2.- print second and last index \
3.- print elements 1-3 \
4.- print all but the first 2 elements \
5.- reshape the array to be a 2x3 matrix 

In [11]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50, 60])

print("Second element (index 1):", arr[1])
print("Last element (index -1):", arr[-1])

print("Elements from index 1 to 3:", arr[1:4])

print("All but the first two elements:", arr[2:])

reshaped_arr = arr.reshape(2, 3)
print("Reshaped to 2x3 matrix:\n", reshaped_arr)


Second element (index 1): 20
Last element (index -1): 60
Elements from index 1 to 3: [20 30 40]
All but the first two elements: [30 40 50 60]
Reshaped to 2x3 matrix:
 [[10 20 30]
 [40 50 60]]


#### Creating random arrays
1- Create a 3x3 matrix with random numbers. \
2.- Create a 2x3 matrix with random integers.


In [12]:

import numpy as np

random_matrix = np.random.rand(3, 3)
print("3x3 Matrix with random decimals:\n", random_matrix)
random_integers = np.random.randint(1, 101, size=(2, 3))
print("\n2x3 Matrix with random integers (1-100):\n", random_integers)


3x3 Matrix with random decimals:
 [[0.39091846 0.32026466 0.47080465]
 [0.84343215 0.03589714 0.52791164]
 [0.7875588  0.98262547 0.93959166]]

2x3 Matrix with random integers (1-100):
 [[96  3 43]
 [46 79 62]]


#### Boolean Indexing and Filtering
1.- Generate a random dataset in a 5x5 matrixs filled with integers from 1-50. \
2.- Filter the values that are bigger than 25 and replace them with 0. \
3.- Calculate the basic statisticañ dispersion and tendency meassurements.

In [13]:
import numpy as np

np.random.seed(42)  
data = np.random.randint(1, 51, size=(5, 5))
print("Original Matrix:\n", data)

Original Matrix:
 [[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]


In [14]:

filtered_data = np.where(data > 25, 0, data)
print("\nFiltered Matrix (values > 25 → 0):\n", filtered_data)


Filtered Matrix (values > 25 → 0):
 [[ 0  0 15  0  8]
 [21  0 19 23 11]
 [11 24  0  0 24]
 [ 3 22  2 24  0]
 [ 0  0  2 21  0]]


In [15]:

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)
min_val = np.min(data)
max_val = np.max(data)

print("\nStatistics (Original Data):")
print(f"Mean: {mean:.2f}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev:.2f}")
print(f"Variance: {variance:.2f}")
print(f"Min: {min_val}")
print(f"Max: {max_val}")


Statistics (Original Data):
Mean: 24.04
Median: 24.0
Standard Deviation: 12.78
Variance: 163.24
Min: 2
Max: 44


#### Homework exercise numpy

⎡ 2  3 ⎤ \
⎣ 0  1 ⎦ 


⎡ 1  2 ⎤  
⎣ 4  0 ⎦ 

1. The product
2. Product's transpose.
3. Determinant of the product
4. The inverse of the product.

In [16]:
import numpy as np

A = np.array([[2, 3], [0, 1]])
B = np.array([[1, 2], [4, 0]])
C = np.dot(A, B) 
print("Product (C = A × B):\n", C)

Product (C = A × B):
 [[14  4]
 [ 4  0]]


In [17]:
C_transpose = C.T
print("\nTranspose of C:\n", C_transpose)


Transpose of C:
 [[14  4]
 [ 4  0]]


In [18]:
det_C = np.linalg.det(C)
print("\nDeterminant of C:", int(det_C))


Determinant of C: -15


In [19]:
inv_C = np.linalg.inv(C)
print("\nInverse of C:\n", inv_C)


Inverse of C:
 [[ 0.     0.25 ]
 [ 0.25  -0.875]]
